In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score

# Tarefa 3 - Neural Networks
Third assessed coursework for the course: Técnicas e Algoritmos em Ciência de Dados

This tarefa provides an exciting opportunity for students to put their knowledge acquired in class into practice, using neural networks to solve real-world problems in both classification and regression. Students will apply the concepts they have learned to build, train, and optimize neural networks, using a validation set to fine-tune hyperparameters. Students will also get used to generating important plots during training to analyse the models' behaviour. By the end of the project, students will have gained hands-on experience in implementing neural networks.

## General guidelines:

* This work must be entirely original. You are allowed to research documentation for specific libraries, but copying solutions from the internet or your classmates is strictly prohibited. Any such actions will result in a deduction of points for the coursework.
* Please enter your code in the designated areas of the notebook. You can create additional code cells to experiment with, but __make sure to place your final solutions where they are requested in the notebook.__
* Before submitting your work, make sure to rename the file to the random number that you created for the previous coursework (for example, 289479.ipynb).3

## Notebook Overview:

1. [Regression](#Regression) (50%)
2. [Classification](#Classification) (50%)

# Regression
## Dataset and Problem Description
In this exercise, you will use the Energy Efficiency Prediction dataset. This dataset contains information about the energy efficiency of buildings based on eight features, including the size of the building, the orientation, and the type of building materials used. The dataset includes two targets: heating load and cooling load, which represent the energy required to heat and cool the building, respectively.
This dataset is useful for building neural networks that predict the energy efficiency of buildings, which is an important problem in the field of sustainable energy. The dataset has been used in several machine learning research papers and provides a challenging regression problem.

## Exercise Description: Energy Efficiency Prediction with Neural Networks
In this exercise, you will use the Energy Efficiency Prediction dataset provided.
You will build and train a neural network to predict the heating load (column labelled y1 in the dataset) and the cooling load (column labelled y2) of a building based on its energy efficiency features. 

**To complete this exercise, you will write code to build and train neural networks for this problem:**

1. Split the dataset into training, validation, and test sets, using a 70:15:15 ratio.

2. Using numpy, build a neural network that takes in the energy efficiency features as input and predicts the heating load as output. You will choose the number of neurons per layers and the number of layers, but each layer will have the same number of neurons.

3. Code the forward pass and backpropagation algorithm to learn the weights of the neural network. Use the training set to train the neural network and update the weights using stochastic gradient descent. You will need to regularize your neural network using weight decay, that is, you will include a regularization term in your error function.

4. Monitor the training by plotting the training and validation losses across the epochs. 


The performance of your neural network will be different depending on the number of layers, number of neurons per layer and the value of λ that controls the amount of weight decay. You will experiment with 3 values of λ: 0 (no weight decay), 0.1 and 0.01.
To choose the best network configuration and assess its performance you will:

1. Calculate the loss for each configuration on the validation set.

2. Generate 3 [heatmaps](https://seaborn.pydata.org/generated/seaborn.heatmap.html) one for each value of the λ regularization parameter, displaying the loss on the validation set by plotting the number of layers and number of neurons in a grid. This will help you visualise the best configuration for the neural network.

3. Train your final model selecting the best combination of hyper-parameters and evaluate the final performance of the neural network using the test set and the root mean squared error as the metric and report that.

**Important:**
* Train for 50 epochs, remember that one epoch finishes when the whole training set was seen during training.
* Set the learning rate $\eta$ to $0.01$.

In [3]:
'''## your code goes here:

#Carregando o código:
EnergyEficciencydf = pd.read_csv('energy_efficiency.csv')
EnergyEficciencydf.head(-1)'''

"## your code goes here:\n\n#Carregando o código:\nEnergyEficciencydf = pd.read_csv('energy_efficiency.csv')\nEnergyEficciencydf.head(-1)"

In [4]:
'''#Fazendo o Split do conjunto de dados.

randomstate = np.random.RandomState(13)


x = EnergyEficciencydf.iloc[:, 0:8]
y = EnergyEficciencydf.iloc[:, 8:10]

#O primeiro split separa o treino com proporção de 70%
x_train, x_validation_test, y_train, y_validation_test = train_test_split(x,y, test_size=0.3, random_state=randomstate)
#O segundo spplit separa o teste e a validação ambos com proporção de 15%
x_validation, x_test, y_validation, y_test = train_test_split(x_validation_test, y_validation_test, test_size=0.5, random_state=randomstate)'''



'#Fazendo o Split do conjunto de dados.\n\nrandomstate = np.random.RandomState(13)\n\n\nx = EnergyEficciencydf.iloc[:, 0:8]\ny = EnergyEficciencydf.iloc[:, 8:10]\n\n#O primeiro split separa o treino com proporção de 70%\nx_train, x_validation_test, y_train, y_validation_test = train_test_split(x,y, test_size=0.3, random_state=randomstate)\n#O segundo spplit separa o teste e a validação ambos com proporção de 15%\nx_validation, x_test, y_validation, y_test = train_test_split(x_validation_test, y_validation_test, test_size=0.5, random_state=randomstate)'

# Classification
## Dataset description: 
This is a dataset from the medical domain. It describes the problem of diagnosing coronary heart disease (CHD ) via Traditional Chinese Medicine approaches. Each datapoint corresponds to a patient represented by a set of 49 features corresponding to the presence or absence of different symptoms: feelings cold or warm, sweating, etc. The 6 labels represent presence or absence of specific heart conditions: deficiency of heart qi syndrome, deficiency of heart yang syndrome, deficiency of heart yin syndrome, qi stagnation syndrome, turbid phlegm syndrome, and blood stasis syndrome.

## Exercise Description: CHD49 Multi-Label Classification with Neural Networks
In this exercise, you will build and train a neural network to predict the 6 different labels of CHD (last 6 columns of the dataset). 

**To complete this exercise, follow these steps:**

1. Load the dataset and split it into training, validation, and test sets, using a 70:15:15 ratio. 

2. Build a neural network using numpy that takes in the features as input and predicts the 6 different labels. You will choose the number of neurons per layers and the number of layers, but each layer will have the same number of neurons.

3. Code the forward pass and backpropagation algorithm to learn the weights of the neural network. Use the training set to train the neural network and update the weights using batch gradient descent. You will choose the number of neurons per layers and the number of layers, but each layer will have the same number of neurons.

4. Monitor the training by plotting the training and validation losses across the epochs. 

The performance of your neural network will be different depending on the number of layers, number of neurons per layer and the value of λ that controls the amount of weight decay. You will experiment with 3 values of λ: 0 (no weight decay), 0.1 and 0.01.
To choose the best network configuration and assess its performance you will:

1. Calculate the loss for each configuration on the validation set.

2. Generate 3 heatmaps, one for each value of the λ regularization parameter, displaying the loss on the validation set by plotting the number of layers and number of neurons in a grid. This will help you visualise the best configuration for the neural network.

3. Train your final model selecting the best combination of hyper-parameters and evaluate the final performance of the neural network using the test set and by calculating the area under the ROC curve, accuracy and F1 score as metrics and report these.

**Important:**
* Train for at least 1000 epochs, remember that one epoch finishes when the whole training set was seen during training.
* Set the learning rate $\eta$ to $0.01$.


In [5]:
## your code goes here:

#Carregando o código:
CHDdf = pd.read_csv('CHD_49.csv')
CHDdf.head(-1)

att1  att2  att3  att4  att5  att6  att7  att8  att9  att10  ...  att46  \
0     1.0  -1.0   1.0  -1.0   1.0   1.0   0.0  -0.5   1.0    1.0  ...    1.0   
1    -1.0  -1.0  -1.0  -1.0   1.0   1.0  -1.0  -1.0  -1.0   -1.0  ...    1.0   
2    -1.0   1.0  -1.0  -1.0   1.0  -1.0  -1.0  -1.0  -1.0   -1.0  ...   -1.0   
3     1.0   1.0  -1.0   1.0  -1.0   1.0   0.0  -0.5   1.0    1.0  ...   -1.0   
4    -1.0  -1.0  -1.0   1.0   1.0   1.0   0.0  -0.5  -1.0    1.0  ...   -1.0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...    ...   
549   1.0   1.0  -1.0  -1.0  -1.0   1.0  -1.0  -1.0  -1.0   -1.0  ...   -1.0   
550   1.0  -1.0  -1.0  -1.0   1.0  -1.0   0.0   0.0   1.0   -1.0  ...   -1.0   
551  -1.0  -1.0  -1.0  -1.0   1.0   1.0  -1.0  -1.0  -1.0   -1.0  ...   -1.0   
552  -1.0  -1.0  -1.0   1.0   1.0   1.0  -1.0  -1.0  -1.0   -1.0  ...   -1.0   
553   1.0   1.0  -1.0  -1.0   1.0   1.0   0.0   0.5   1.0    1.0  ...   -1.0   

     att47  att48  att49  label1  label2  label3  label4  label5  label6  
0      1.0    1.0    1.0     1.0     0.0     1.0     0.0     1.0     1.0  
1      1.0    1.0   -1.0     1.0     0.0     0.0     1.0     0.0     0.0  
2      1.0   -1.0    1.0     0.0     1.0     0.0     0.0     0.0     1.0  
3      1.0    1.0   -1.0     0.0     1.0     0.0     0.0     0.0     1.0  
4     -1.0   -1.0   -1.0     0.0     0.0     1.0     0.0     0.0     1.0  
..     ...    ...    ...     ...     ...     ...     ...     ...     ...  
549    1.0    1.0   -1.0     1.0     0.0     1.0     0.0     0.0     1.0  
550   -1.0   -1.0   -1.0     1.0     0.0     0.0     0.0     0.0     1.0  
551   -1.0   -1.0   -1.0     1.0     0.0     0.0     0.0     0.0     1.0  
552    1.0   -1.0    1.0     0.0     0.0     0.0     0.0     0.0     0.0  
553    1.0   -1.0    1.0     1.0     0.0     1.0     0.0     0.0     1.0  

[554 rows x 55 columns]

In [6]:
#Fazendo o Split do conjunto de dados.

randomstate = np.random.RandomState(13)


x = CHDdf.iloc[:, 0:49]
y = CHDdf.iloc[:, 49:55]

#O primeiro split separa o treino com proporção de 70%
x_train, x_validation_test, y_train, y_validation_test = train_test_split(x,y, test_size=0.3, random_state=randomstate)
#O segundo spplit separa o teste e a validação ambos com proporção de 15%
x_validation, x_test, y_validation, y_test = train_test_split(x_validation_test, y_validation_test, test_size=0.5, random_state=randomstate)

In [7]:
#Inicializando os nossos parâmetros de pesos e vieses

def initialize_weights(x, y, hidden_neurons):
    W1 = np.random.randn(x, hidden_neurons[0])
    b1 = np.zeros((1, hidden_neurons[0]))
    
    W2 = np.random.randn(hidden_neurons[0], hidden_neurons[1])
    b2 = np.zeros((1, hidden_neurons[1]))
    
    W3 = np.random.randn(hidden_neurons[1], y)
    b3 = np.zeros((1, y))

    return W1, W2, W3, b1, b2, b3


In [78]:
# Criando a Foward Propagation usando a função de ativação sigmoid
def sigmoid(Z):
    return 1 / (1 + np.exp(-Z))
# Derivada da função de ativação sigmoid
def sigmoid_derivative(Z):
    return sigmoid(Z) * (1 - sigmoid(Z))

def forward_propagation(X, W1, W2, W3, b1, b2, b3):
    Z1 = np.dot(X, W1) + b1
    A1 = sigmoid(Z1)
    Z2 = np.dot(A1, W2) + b2
    A2 = sigmoid(Z2)
    Z3 = np.dot(A2, W3) + b3
    output_layer = sigmoid(Z3)

    return Z1, Z2, Z3, A1, A2, output_layer

def back_propagation(X, y, output_layer, W3, W2, W1, A2, A1, b3, b2, b1, learning_rate):
    output_error = y - output_layer
    output_delta = output_error * sigmoid_derivative(output_layer)

    hidden_error2 = output_delta.dot(W3.T)
    hidden_delta2 = hidden_error2 * sigmoid_derivative(A2)

    hidden_error1 = hidden_delta2.dot(W2.T)
    hidden_delta1 = hidden_error1 * sigmoid_derivative(A1)

    W3 += A2.T.dot(output_delta) * learning_rate
    W2 += A1.T.dot(hidden_delta2) * learning_rate
    W1 += X.T.dot(hidden_delta1) * learning_rate
    b3 += np.sum(np.sum(output_delta, axis=0) * learning_rate)
    b2 += np.sum(np.sum(A2, axis=0) * learning_rate)
    b1 += np.sum(np.sum(A1, axis=0) * learning_rate)

    return W1, W2, W3, b1, b2, b3, output_layer, output_error

In [81]:
def train(x, y, epochs, learning_rate, hidden_neurons):
    xshape = x.shape[1]
    yshape = y.shape[1]
    w1, w2, w3, b1, b2, b3 = initialize_weights(xshape, yshape, hidden_neurons)
    for i in range(epochs):
        Z1, Z2, Z3, A1, A2, output_layer = forward_propagation(x, w1, w2, w3, b1, b2, b3)

        w1, w2, w3, b1, b2, b3, output_layer, output_error = back_propagation(x, y, output_layer, w3, w2, w1, A2, A1, b3, b2, b1, learning_rate)

    return w1, w2, w3, b1, b2, b3

def predict(X, w1, w2, w3, b1, b2, b3):
    Z1, Z2, Z3, A1, A2, output_layer = forward_propagation(X, w1, w2, w3, b1, b2, b3)
    return output_layer

In [80]:
epochs = 500
learning_rate = 0.1
hidden_neurons = [10, 10]

w1, w2, w3, b1, b2, b3 = train(x_train, y_train, epochs, learning_rate, hidden_neurons)

[[0.89911791 0.21347609 0.20550642 0.58478095 0.74341093 0.17339852]
 [0.86895703 0.47167302 0.09756638 0.69779751 0.75501375 0.49975988]
 [0.9000538  0.21052773 0.21085889 0.80747459 0.81500707 0.43021326]
 ...
 [0.87742174 0.25711464 0.16587046 0.90508152 0.73680512 0.29868097]
 [0.97786439 0.17284493 0.21955903 0.58842198 0.80359093 0.22668824]
 [0.90612046 0.18354997 0.26154128 0.58377594 0.84601706 0.22954717]]
       label1    label2    label3    label4    label5    label6
505 -0.899118  0.786524 -0.205506 -0.584781 -0.743411  0.826601
491 -0.868957  0.528327 -0.097566 -0.697798 -0.755014 -0.499760
316  0.099946 -0.210528 -0.210859  0.192525 -0.815007 -0.430213
456  0.101727 -0.113401  0.617515 -0.432094 -0.928616 -0.282900
214  0.125633 -0.456141  0.893947 -0.678799  0.311209  0.690875
..        ...       ...       ...       ...       ...       ...
153  0.043646 -0.263242 -0.156352 -0.367185 -0.796001  0.800033
528  0.183819 -0.208308 -0.278843 -0.919978  0.172556 -0.260294
74  